# Generated by Django 4.2.7 on 2023-11-22 12:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenter', models.CharField(max_length=100)),
                ('date_commented', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', tinymce.models.HTMLField()),
                ('date', models.DateField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
