# Generated by Django 4.2.4 on 2023-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_commented',
            field=models.DateField(auto_now_add=True),
        ),
    ]
